"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Calendar, DollarSign, Loader2, Package, Search, Shield, User, X } from "lucide-react";

type Result = { id: string; type: "member" | "role" | "event" | "finance" | "inventory"; title: string; description: string; href: string };
const icons = { member: User, role: Shield, event: Calendar, finance: DollarSign, inventory: Package };

export function GlobalSearchInput() {
  const router = useRouter();
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Result[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [active, setActive] = useState(0);
  const requestRef = useRef(0); const rootRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (e: MouseEvent) => { if (!rootRef.current?.contains(e.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  useEffect(() => { const value = query.trim(); if (value.length < 2) { setResults([]); setError(null); return; } const request = ++requestRef.current; const timer = setTimeout(async () => { setLoading(true); setError(null); try { const res = await fetch(`/api/search?q=${encodeURIComponent(value)}`); const payload = await res.json(); if (!res.ok) throw new Error(payload.message ?? "Search failed."); if (request === requestRef.current) { setResults(payload?.items ?? payload?.data?.items ?? []); setActive(0); } } catch (e) { if (request === requestRef.current) setError(e instanceof Error ? e.message : "Search failed."); } finally { if (request === requestRef.current) setLoading(false); } }, 300); return () => clearTimeout(timer); }, [query]);
  const select = (item: Result) => { setOpen(false); router.push(item.href); };
  const onKeyDown = (e: React.KeyboardEvent) => { if (e.key === "Escape") setOpen(false); if (!results.length) return; if (e.key === "ArrowDown") { e.preventDefault(); setActive(i => (i + 1) % results.length); } if (e.key === "ArrowUp") { e.preventDefault(); setActive(i => (i - 1 + results.length) % results.length); } if (e.key === "Enter") { e.preventDefault(); select(results[active]); } };
  return <div ref={rootRef} className="relative w-full" onKeyDown={onKeyDown}><div className="relative flex h-11 items-center gap-3 rounded-full border border-border bg-card px-4 text-sm focus-within:ring-2 focus-within:ring-ring"><Search className="h-4 w-4 text-secondary-foreground" /><input value={query} onChange={e => { setQuery(e.target.value); setOpen(true); }} onFocus={() => setOpen(true)} placeholder="Search workspace..." className="w-full bg-transparent focus:outline-none" />{loading && <Loader2 className="h-4 w-4 animate-spin" />}{query && <button aria-label="Clear search" onClick={() => { setQuery(""); setResults([]); }}><X className="h-4 w-4" /></button>}</div>{open && query.trim().length >= 2 && <div className="absolute z-50 mt-2 max-h-96 w-full overflow-y-auto rounded-2xl border border-border bg-card p-2 shadow-xl">{error && <p className="p-4 text-sm text-destructive">{error}</p>}{!loading && !error && !results.length && <p className="p-4 text-center text-sm text-secondary-foreground">No matching results found.</p>}{results.map((item, i) => { const Icon = icons[item.type]; return <button key={`${item.type}-${item.id}`} onMouseEnter={() => setActive(i)} onClick={() => select(item)} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left ${i === active ? "bg-secondary" : "hover:bg-secondary"}`}><Icon className="h-4 w-4" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{item.title}</span><span className="block truncate text-xs text-secondary-foreground">{item.description}</span></span><span className="text-[10px] uppercase text-secondary-foreground">{item.type}</span></button>; })}</div>}</div>;
}
